default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary: &production_default
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cache:
    <<: *production_default
    migrations_paths: db/cache_migrate
  queue:
    <<: *production_default
    migrations_paths: db/queue_migrate
  cable:
    <<: *production_default
    migrations_paths: db/cable_migrate
