service: vorla_rails
image: vorla_rails

servers:
  web:
    - 173.242.57.115

proxy:
  ssl: true
  host: x-ror.fun

registry:
  server: 173.242.57.115:5000
  username: kamal
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    APP_HOST: x-ror.fun
    WEBAUTHN_ORIGIN: https://x-ror.fun
    WEBAUTHN_RP_ID: x-ror.fun

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "vorla_rails_storage:/rails/storage"

asset_path: /rails/public/assets

ssh:
  keys:
    - ~/.ssh/id_ed25519_vorla

builder:
  arch: amd64
  remote: ssh://root@173.242.57.115

accessories:
  registry:
    image: registry:2
    host: 173.242.57.115
    port: "127.0.0.1:5000:5000"
    volumes:
      - "kamal_registry:/var/lib/registry"
